# Benchmarks - Preprocess DB

**Main considerations when implementing Preprocess DB**

The goal of preprocess_db is to go from a pandas dataframe with columns "Task_ID", "Input", "Input_ID", "Output" and "Output_ID" to a set of tensors containing all inputs, padded inputs, padded outputs and mappings, that can be used throughout the MagmaClustPy library.

Magma and MagmaClust both work on unaligned sequences of varying sizes.
Yet, we want to be able to perform as many operations in a vectorisable and jittable way.

This mean that we need to pad the sequences to the same length.
The most straightforward way to do this is to align the sequences to the union of all distinct inputs, but this leads to a huge memory footprint and costly data movement in and out of the GPU.
A better way is to pad the sequences to the maximum length among all task sequences, and use a mapping of indices when we need to align the inputs to the union of all inputs.

As MagmaClust can handle multi-input tasks, we need multiple mappings, one for each input.
The union of all inputs from a specific dimension will have a specific length, but once again we want to be able to store them in a single tensor.
This means that even the grid of all_inputs must be padded to the maximum length across all dimensions of inputs.

---
## Setup

In [1]:
USE_X64 = False  # Set to True to use 64-bit precision, False for 32-bit precision

In [2]:
# Standard library
import os

# Config
os.environ['JAX_ENABLE_X64'] = str(USE_X64).lower()

from functools import partial

In [3]:
# Third party
import jax
from jax import vmap, jit
import jax.numpy as jnp
import jax.random as jr
from jax.lax import cond

import numpy as np
import pandas as pd

In [4]:
# Config
key = jax.random.PRNGKey(0)
test_db_size = "large"

In [5]:
# Set constants
M = 2  # Number of tasks
INPUTS_ID = ["x"]  # Each dimension of inputs
MIN_N = 3  # Minimum inputs per task
MAX_N = 5  # Maximum inputs per task
OUTPUTS_ID = ["a", "b"]  # Each dimension of outputs
GRIDS = [jnp.arange(-5., 5., 1.), jnp.arange(-1., 1., 0.5), jnp.arange(0., 2., 1)]  # Grid to pick inputs from, for each input dimension
OUTPUT_RANGES = [(-5, 5), (-10, 10)]  # Ranges for outputs, for each output dimension

---
## Data

In [6]:
from MagmaClustPy.utils import generate_dummy_db

In [7]:
db = generate_dummy_db(M, INPUTS_ID, MIN_N, MAX_N, OUTPUTS_ID, GRIDS, OUTPUT_RANGES, 0.25, key)
db

   Task_ID  Input Input_ID    Output Output_ID
0        0   -2.0        x -4.696017         a
1        0   -2.0        x  2.939410         b
2        1    0.0        x -2.760121         a
3        1    0.0        x -2.639604         b
4        1   -4.0        x -4.766386         b
5        1    2.0        x -3.690923         a
6        1   -1.0        x  4.828791         a

---
## Current Implementation

In [8]:
import MagmaClustPy

preprocess_db_old = MagmaClustPy.utils.preprocess_db

---
## Custom implementation(s)

We transition to a multi-input multi-output setting

In [9]:
# Functions that we don't change this time
from MagmaClustPy.utils import pivot_db
from MagmaClustPy.linalg import searchsorted_2D, searchsorted_2D_vectorized, compute_mapping

In [10]:
flat_db = pivot_db(db)
flat_db

   Task_ID  Input_x  Output_a  Output_b
0        0     -2.0 -4.696017  2.939410
1        1     -4.0       NaN -4.766386
2        1     -1.0  4.828791       NaN
3        1      0.0 -2.760121 -2.639604
4        1      2.0 -3.690923       NaN

In [11]:
# Dimensions:
# T : the tasks
# N : the number of all observations across all tasks
# MAX_N_I : the maximum number of inputs per tasks
# I : dimensions of inputs
# O : dimensions of outputs

In [14]:
@partial(jit, static_argnames=["max_n_i"])
def extract_task_data(_id, task_ids, input_values, output_values, all_inputs, max_n_i):
	"""
	Extract data for a given task ID from the values array and return a row of padded inputs, padded outputs and index_mappings.

	:param _id: the task ID to extract data for
	:param task_ids: the array of the task id of each observation (shape: (N, 1))
	:param input_values: the input values for all tasks  (shape: (T, N, I))
	:param output_values: the output values for all tasks (shape: (T, N, O))
	:param all_inputs: the array of all distinct inputs (shape: (P, I))
	:param max_n_i: the maximum number of inputs per task (scalar)

	:return: a tuple of (padded_input, padded_output, index_mappings)
	   - padded_input: a matrix of shape (MAX_N_I, I) with inputs for the task, padded with NaNs
	   - padded_output: a matrix of shape (MAX_N_I, O) with corresponding outputs for each input, padded with NaNs
	   - index_mappings: a matrix of shape (MAX_N_I,) with indices of the inputs in the all_inputs array. Missing inputs for the task are represented as NaNs.
	"""
	inputs_i = jnp.where(task_ids == _id, input_values, jnp.nan)
	outputs_i = jnp.where(task_ids == _id, output_values, jnp.nan)
	mappings_i = compute_mapping(all_inputs, input_values)

	# Compute index among the whole dataset
	idx_i = jnp.where(jnp.isnan(inputs_i[:, 0]), max_n_i + 1, jnp.cumsum(~jnp.isnan(inputs_i[:, 0])) - 1)

	# Create padded inputs and outputs
	padded_input = jnp.full((max_n_i, inputs_i.shape[-1]), jnp.nan).at[idx_i].set(inputs_i)
	padded_output = jnp.full((max_n_i, outputs_i.shape[-1]), jnp.nan).at[idx_i].set(outputs_i)
	index_mappings = jnp.full((max_n_i,), all_inputs.shape[0] + 1).at[idx_i].set(mappings_i).astype(int)

	return padded_input, padded_output, index_mappings

In [15]:
def preprocess_db(db: pd.DataFrame):
	"""

	:param db:
	:return:
	"""
	# Pivot the database
	db_flat = pivot_db(db)

	# Get task IDs
	task_ids = jnp.array(db_flat["Task_ID"].values, dtype=jnp.int32)[:, None]  # Convert to column vector

	# Get inputs and outputs
	inputs = jnp.array(db_flat.filter(like="Input_").values, dtype=jnp.float32)
	outputs = jnp.array(db_flat.filter(like="Output_").values, dtype=jnp.float32)

	# Get all distinct inputs
	all_inputs = jnp.unique(db_flat.sort_values(by=[col for col in db_flat if col.startswith("Input_")]).filter(like="Input_").values, axis=0)

	# Get maximum number of inputs per task
	MAX_N = jnp.max(jnp.sum(task_ids == task_ids[0], axis=0)).item()  # Maximum number of inputs per task

	# Recover padded inputs, padded outputs and index mappings
	return vmap(extract_task_data, in_axes=(0, None, None, None, None, None))(jnp.unique(task_ids), task_ids, inputs, outputs, all_inputs, MAX_N) + (all_inputs,)

In [16]:
preprocess_db_new = preprocess_db

---
## Comparison

In [17]:
padded_inputs_1, padded_outputs_1, masks_1, all_inputs_1 = preprocess_db_old(db)
padded_inputs_1.shape, padded_outputs_1.shape, masks_1.shape, all_inputs_1.shape

((2, 1, 1), (2, 1, 2), (2, 1), (5, 1))

In [18]:
padded_inputs_2, padded_outputs_2, masks_2, all_inputs_2 = preprocess_db_new(db)
padded_inputs_2.shape, padded_outputs_2.shape, masks_2.shape, all_inputs_2.shape

((2, 1, 1), (2, 1, 2), (2, 1), (5, 1))

In [19]:
jnp.allclose(padded_inputs_1, padded_inputs_2, equal_nan=True), \
jnp.allclose(padded_outputs_1, padded_outputs_2, equal_nan=True), \
jnp.allclose(masks_1, masks_2, equal_nan=True), \
jnp.allclose(all_inputs_1, all_inputs_2, equal_nan=True)

(Array(True, dtype=bool),
 Array(True, dtype=bool),
 Array(True, dtype=bool),
 Array(True, dtype=bool))

**Performance on the generated db**

In [20]:
%timeit preprocess_db_old(db)[0].block_until_ready()

5.61 ms ± 252 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [21]:
%timeit preprocess_db_new(db)[0].block_until_ready()

KeyboardInterrupt:

**Performances on a dummy dataset**

In [20]:
dummy_db = pd.read_csv(f"../datasets/{test_db_size}_distinct_input_shared_hp.csv")

In [21]:
%timeit preprocess_db_old(dummy_db)[0].block_until_ready()

39.8 s ± 625 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [22]:
%timeit preprocess_db_new(dummy_db)[0].block_until_ready()

7.11 s ± 248 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

---